dist: trusty

sudo: required

services:
  - postgresql
  
addons:
  postgresql: "9.6"

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"
  
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cd decide
  - python manage.py migrate
  
language: python

python:
  - "3.6"
  
install:
  - pip install -r requirements.txt
  
script:
  - python manage.py test store
